<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Create a shortcut for params.
$params  = &$this->item->params;
$canEdit = $this->item->params->get('access-edit');
$info    = $this->item->params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
	|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate())) : ?>
	<div class="system-unpublished">
<?php 
endif;
if ($params->get('show_title')) :
?>

	<h1 itemprop="headline">
<?php 
	if ($params->get('link_titles') && $params->get('access-view')) :
?>
		<a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>" itemprop="url"><?php echo $this->escape($this->item->title); ?></a>
<?php 
	else :
		echo $this->escape($this->item->title);
	endif;
?>
	</h1>
<?php
endif;
if ($this->item->state == 0) : ?>
	<span class="label label-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
<?php 
endif;
if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?>
	<span class="label label-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
<?php 
endif;
if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?>
	<span class="label label-warning"><?php echo JText::_('JEXPIRED'); ?></span>
<?php 
endif;
// Content is generated by content plugin event "onContentAfterTitle"
echo $this->item->event->afterDisplayTitle;
// Todo Not that elegant would be nice to group the params
$useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
	|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam);
if ($useDefList && ($info == 0 || $info == 2)) :
	// Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block
	echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above'));
endif;
if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) :
	echo JLayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags);
endif;
echo JLayoutHelper::render('joomla.content.intro_image', $this->item);

// Content is generated by content plugin event "onContentBeforeDisplay"
echo $this->item->event->beforeDisplayContent;
echo $this->item->introtext;
if ($info == 1 || $info == 2) :
	if ($useDefList) :
		// Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block
		echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below'));
	endif;
	if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) :
		echo JLayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags);
	endif;
endif;

if ($params->get('show_readmore') && $this->item->readmore) :
	if ($params->get('access-view')) :
		$link = JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language));
	else :
		$menu = JFactory::getApplication()->getMenu();
		$active = $menu->getActive();
		$itemId = $active->id;
		$link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
		$link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
	endif;
	echo JLayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link));
endif;
if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
	|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != $this->db->getNullDate() )) : ?>
	</div>
<?php
endif;
// Content is generated by content plugin event "onContentAfterDisplay"
echo $this->item->event->afterDisplayContent; ?>
