<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Create shortcuts to some parameters.
$params  = $this->item->params;
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');

?>
	<article itemscope itemtype="https://schema.org/Article">
		<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
<?php
	if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative)
	{
		echo $this->item->pagination;
	}
	$useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
	|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam);
	
	if ($params->get('show_title')) :
?>
		<h1 itemprop="headline"><?php echo $this->escape($this->item->title); ?></h1>
<?php
	endif;

	echo $this->item->event->afterDisplayTitle;

//Bloque de INFO del artículo
	if ($useDefList && ($info == 0 || $info == 2)) :
	// Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block
		echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above'));
	endif;

//TAGS
	if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) :
		$this->item->tagLayout = new JLayoutFile('joomla.content.tags');
		echo $this->item->tagLayout->render($this->item->tags->itemTags);
	endif;

// Content is generated by content plugin event "onContentBeforeDisplay"
	echo $this->item->event->beforeDisplayContent;
	if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
		|| (empty($urls->urls_position) && (!$params->get('urls_position')))) :
		echo $this->loadTemplate('links');
	endif;

//Full Article Image
	if ($params->get('access-view')) :
		echo JLayoutHelper::render('joomla.content.full_image', $this->item);
		if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) :
			echo $this->item->pagination;
		endif;
		if (isset ($this->item->toc)) :
			echo $this->item->toc;
		endif;
?>
	<div itemprop="articleBody">
		<?php echo $this->item->text; ?>

	</div>

<?php
		if ($info == 1 || $info == 2) :
			if ($useDefList) :
				// Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block
				echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below'));

			endif;
			if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) :
				$this->item->tagLayout = new JLayoutFile('joomla.content.tags');
				echo $this->item->tagLayout->render($this->item->tags->itemTags);
			endif;
		endif;

//Paginación (Anterior, Siguiente)
		/*
		if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative) :
			echo $this->item->pagination;
		endif;
		*/

		if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) :
			echo $this->loadTemplate('links');
		endif;

// Optional teaser intro text for guests
	elseif ($params->get('show_noauth') == true && $user->get('guest')) :
		echo JLayoutHelper::render('joomla.content.intro_image', $this->item);
		echo JHtml::_('content.prepare', $this->item->introtext);
	// Optional link to let them register to see the whole article.
		if ($params->get('show_readmore') && $this->item->fulltext != null) :
			$menu = JFactory::getApplication()->getMenu();
			$active = $menu->getActive();
			$itemId = $active->id;
			$link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
			$link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
?>
	<p class="readmore">
		<a href="<?php echo $link; ?>" class="register">
<?php
			if ($params->get('alternative_readmore', '') === '') :
				echo JText::_('COM_CONTENT_REGISTER_TO_READ_MORE');
			else :
				echo $params->get('alternative_readmore');
				if ($params->get('show_readmore_title', 0) != 0) :
					echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
				endif;
			endif;
?>
		</a>
	</p>
<?php
		endif;
	endif;

	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) :
		echo $this->item->pagination;
	endif;
	echo $this->item->event->afterDisplayContent;
?>
	</article>
